language: ruby
sudo: false
rvm:
- 2.1.0
- 2.2.0
- ruby-head
cache:
  bundler: true
  bundler_args: --jobs=3 --retry=3 --without development
matrix:
  allow_failures:
  - rvm: ruby-head
  fast_finish: true
notifications:
  email: false
  slack:
    secure: abQCnENgJqoC0zqHB565x7pQLpBgCHU8czcM7ReZxm6ArJr/lt/rUg2100mAHxBhfZoAlzRvZ3jHfLjmcNf8p+cxSuflqLcgpm8JyA01zeFzkrphB5LP2kES78aLZlll1khb9CySy2nwNetkm0Qkp1OdIvlmOSynvRGIP4JCMQBfno+sTMVChRgUPKeoQ6bNP7UEXRsBoccT1qyK/YjKCBlawZdFrRbbEmqAtRQu7OwwjpAe6pmt9E+srjQtmIHOQYys/LiN+Mp6yKF9weqpvH5h30CkaU6n2jDkbnZyrtUJKzkcaALMeNVawFi7vf6rEdN8fdm1yO+AGJBZWzrJkpnrtCm/+i7k5ix2ho6RQAvzNotq2Exe1Jl/X3RliSzGHh6xQmYHXWCM51qOqxe8t8T69r5SrVyr8ZvXy3y62GNSCNlJiWgjeeU7gpGZUeUZAt5qSDJh5vrplBFEhTR+aV6PJ7GWa3AYCN1NdKvt1lh7N0285haoC1fDS/Q2+CJHZJjg03qLf7idKC041xrEV/0mPYWU4K76GrFS/EJwLQnrRdHJ6kg86850kgREz6+8EKIM4NmLJbJHDU5ivQug8QaD+DumVLYDL+gnDRradJYY7tYFsBnEHXs+qEIl16cla3fwdqezn25FWxONebv+F6xdZXEKmSKZzYffumG41LQ=
addons:
  postgresql: '9.3'
