app:
  build: .
  command: bin/rails server -p 3000 -b '0.0.0.0'
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - postgres
  environment:
    DATABASE_URL: "postgres://postgres@postgres:5432/rubytw-reboot_dev"
postgres:
  image: postgres:9.4
  ports:
    - "5432"
